### ISSUE TITLE
Loading rows in batches

### ISSUE THREAD

**Issue by ankushgarg1998** [FranzDiebold/ng-google-sheets-db-library#17]
Hey @FranzDiebold 

Great work on the library!
Wanted to know if there's a way we can fetch only a few rows at a time.

My Use Case:
I have a very large sheet (about 5,000 rows). And I want to display data of only 10 rows at a time.
Following a trigger, I would want to load the next 10 rows and so on...

Is that possible using this library?

**Comment by FranzDiebold** [comment]
Hi @ankushgarg1998 ,

thanks for your appreciation! 🎉 

I understand your use case!
However, it is not possible to load data batch-wise in `ng-google-sheets-db`.

Technical background:
Under the hood, the [Google Sheets API](https://developers.google.com/sheets/api) is used. It supports partial data loading using the ["A1" syntax](https://developers.google.com/sheets/api/guides/concepts#expandable-1), but unfortunately groups are not supported (i.e. first row *and* row 30-39). Since the first row is used as header to infer the attribute names, it would not be possible to i.e. load items 30-39 including the header in one request. So either two requests or an internal state would be needed.

Nevertheless, I want to save this in the [feature request list](https://github.com/FranzDiebold/ng-google-sheets-db-library/wiki/Feature-requests) in the wiki so that it doesn't get lost! 😉

**Comment by ankushgarg1998** [comment]
Understood. Thanks :D
