### ISSUE TITLE
Update Call Implementation

### ISSUE THREAD

**Issue by mfbatra** [FranzDiebold/ng-google-sheets-db-library#5]
Is it also possible to extend the update call within the library?

**Comment by FranzDiebold** [comment]
Hi @mfbatra, thanks for you comment! What do you exactly mean with "update call"?

**Comment by mfbatra** [comment]
Hi @FranzDiebold , I am looking to perform a "PUT" call for my use case. That's why I wanted to update a few rows as well.

**Comment by FranzDiebold** [comment]
Now I understand you @mfbatra .

Since this library is meant to make "*Google Sheets [...] your **read-only** backend for your Angular app!*" (see project description) I would not change the library accordingly.

The "*read-only*" has several reasons:
1. If you want to update a Google Sheet you need to either ...
    - authenticate to Google Sheets, which would mean that the user needs to login. This is too complicated, we do not want to do this.
    - or use a token. The token would need to be part of the Angular app and would thus be public. We do not want to do this.
2. Internally, the library uses a Google Sheets JSON feed to load the data. This feed is by definition read-only. It does not use the Google Sheets API.
3. Keep the library simple. In most cases, you just want to load data and not change it.
